[package]
name = "floem_vger"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia = "0.8.3"
resvg = "0.29.0"
wgpu = "0.15.1"
raw-window-handle = "0.5.1"
futures = "0.3.26"
anyhow = "1.0.69"
vger = { git = "https://github.com/lapce/vger-rs", rev = "25696dc6cf79da499d466646cc4b0b30e5225d6a" }
peniko = { git = "https://github.com/linebender/peniko", rev = "cafdac9a211a0fb2fec5656bd663d1ac770bcc81" }
parley = { git = "https://github.com/lapce/parley", rev = "dd30cc9e4ae733d80650ad3ab0db0462ccd67e57" }
swash = { git = "https://github.com/dfrg/swash" }
cosmic-text = { git = "https://github.com/lapce/cosmic-text", rev = "6b1dbb529a2396378c05e452b5dc82376ee25040" }
floem_renderer = { path = "../renderer" }
