[package]
name = "floem_vger"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia = "0.8.3"
resvg = "0.29.0"
wgpu = "0.15.1"
raw-window-handle = "0.5.1"
futures = "0.3.26"
anyhow = "1.0.69"
peniko = { git = "https://github.com/linebender/peniko", rev = "cafdac9a211a0fb2fec5656bd663d1ac770bcc81" }
swash = { git = "https://github.com/dfrg/swash" }
vger = { git = "https://github.com/lapce/vger-rs", rev = "0def344b26c97cbab76503d80fd0f1de83c6d41e" }
# vger = { path = "../../vger-rs" }
floem_renderer = { path = "../renderer" }
