[package]
name = "floem"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
indexmap = "1.9.2"
rustc-hash = "1.1.0"
smallvec = "1.10.0"
educe = "0.4.20"
parley = { git = "https://github.com/dfrg/parley" }
taffy = { git = "https://github.com/DioxusLabs/taffy" }
leptos_reactive = { version = "0.1.3", features = ["stable"] }
glazier = { git = "https://github.com/linebender/glazier" }
vello = { git = "https://github.com/linebender/vello" }
wgpu = "0.15"
tokio = { version = "1.21", features = ["full"] }

[workspace]
members = [
  "examples/*",
]