[package]
name = "floem_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
usvg = "0.29.0"
peniko = { git = "https://github.com/linebender/peniko", rev = "cafdac9a211a0fb2fec5656bd663d1ac770bcc81" }
cosmic-text = { git = "https://github.com/lapce/cosmic-text", rev = "5344eab79a6f805a56e4fd3374edc695d9e73bdf" }
# cosmic-text = { path = "../../cosmic-text" }
